media: media
content:
  - name: pages
    label: Pages
    type: collection
    path: pages
    filename: "{title}.md"
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text